services:
  gradspaceBK:
    image: fragger0497/gradspace:backend
    container_name: gradspaceBK
    ports:
      - "8000:8003"
    restart: always
    env_file:
      - .env
    volumes:
      - ./templates:/app/templates
